# Generated by Django 2.1.1 on 2018-10-22 13:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('departure', models.DateField(default=datetime.datetime.now)),
                ('arrival', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('licence', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YouApp.Department', verbose_name='list of departments')),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speedometer', models.IntegerField()),
                ('litres', models.FloatField()),
                ('cost', models.FloatField()),
                ('reading_on', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_of_service', models.CharField(choices=[('MINOR', 'Minor'), ('MEDIUM', 'Medium'), ('MAJOR', 'Major')], default='MINOR', max_length=2)),
                ('comment', models.TextField()),
                ('published_on', models.DateField(default=datetime.datetime.today)),
                ('serviced_on', models.DateField(default=datetime.datetime.now)),
                ('scheduled_service', models.FloatField()),
                ('cost', models.FloatField()),
                ('defect_report', models.TextField(blank=True, default='No Defect Reported')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('year_make', models.CharField(max_length=50)),
                ('chassis', models.CharField(max_length=30)),
                ('purchase_price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YouApp.Vehicle', verbose_name='list of vehicles'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YouApp.Vehicle', verbose_name='list of vehicles'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YouApp.Driver', verbose_name='list of drivers'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YouApp.Vehicle', verbose_name='list of vehicles'),
        ),
    ]
