# Generated by Django 2.1.1 on 2018-10-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='details_of_service',
            field=models.CharField(choices=[('MI', 'Minor'), ('ME', 'Medium'), ('MA', 'Major')], default='MI', max_length=2),
        ),
    ]
