# Generated by Django 2.1.1 on 2018-10-11 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='defect_report',
            field=models.TextField(blank=True, default='No Defect Reported'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='arrival',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='departure',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='reading_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='service',
            name='scheduled_service',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='serviced_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
